/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/BRCA/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/BLCA/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/LIHC/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/LUAD/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/PAAD/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/GBM/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/UCS/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/LAML/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/HNSC/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/OV/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/READ/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/PRAD/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/KICH/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/ESCA/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/KIRC/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/LUSC/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/CESC/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/COAD/
/DAS/TBlab/Touati/TCGA/MethylationNormalization/Input/STAD/
